### ISSUE TITLE
Úprava zadání atributu pro R

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#35]
Subset má hodnotu jen 1-1 => přejmenovat na "Any value", skrýt inputy

**Comment by PreVaDu** [comment]
Až to bude aktuální, prosím o bližší vysvětlení, nevím kde se ten atribut zadává...

**Comment by vojir** [comment]
Jde o zadání jakéhokoliv atributu v případě, kdy je jako backendová dolovací komponenta použito R.

R nepodporuje spojování hodnot v atributech, tato funkce je korektně zakázána prostřednictvím FeatureListu. Ale inputy jsou v takovém případě poněkud matoucí..

**Comment by PreVaDu** [comment]
Mohu se zeptat kde přesně je informace o nepodporování spojování hodnot k nalezení ve FL?
V principu si mohu porovnat (ačkoliv mi to z neznámého důvodu zlobilo) minLength.minValue a maxLength.maxValue, pokud jsou shodné, tak nemá smysl vykreslovat inputy. Nebo bylo něco přesnějšího? Mám dávat podmínku pouze pro subset?

Když to zjistím, napadají mě 3 možnosti, jak to celé udělat:
1) přepsat na Any value v selectu a nic už dál nevykreslovat
2) nechat subset a pod to napsat "only value 1" nebo tak něco
3) nechat subset a pod to napsat jen jeden input s jedničkou a labelem "number of values"

**Comment by vojir** [comment]
Ve feature listu je to zadáno jako min=1 a max=1. Kontrola by měla být, zda maximum=1.
Z hlediska zobrazení bych byl pro variantu 1), tj. v selectu napsat "Any value" a další prvky nevykreslovat.

**Comment by vojir** [comment]
V nastavení BBA je u daného nastavení nově k dispozici boolean proměnná "hidden". Pokud je nastavená na true, měl by být do formuláře v daném dialogu přidán místo viditelného inputu input typu hidden s příslušnou výchozí hodnotou.

**Comment by PreVaDu** [comment]
Hotovo.

**Comment by vojir** [comment]
funguje v dialogu při přidání atributu, ale ne při jeho změně (při použití editace atributu, který už je umístěn v pravidle)

**Comment by PreVaDu** [comment]
Doděláno, navíc sjednoceny boxy add a edit do "add" podoby...

**Comment by vojir** [comment]
ověřeno
