### ISSUE TITLE
Problematická deaktivace drop zóny v attributes palete

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#39]
V některých případech nedojde k deaktivaci zeleného podbarvení palety atributů (při zobrazení histogramu, kliknutí na + pro přidání datového sloupce do atributů atp.

**Comment by vojir** [comment]
Paleta zůstane aktivovaná při přidání atributu ne pomocí přetažení, ale pomocí kliknutí na + u položky v data fields

**Comment by PreVaDu** [comment]
Pravděpodobně opraveno v rámci zrušení animaci u #46.
