### ISSUE TITLE
Nezobrazování dialogu pro změnu spojky, pokud ji není možné změnit 

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#40]
Pokud není možné změnit spojku v rámci zadání vzoru pravidel, neměla by být spojka "klikatelná" (tj. neměl by se zobrazovat dialog pro změnu spojky, který poté obsahuje prázdný select)

**Comment by PreVaDu** [comment]
Nastavil jsem to tak, že by se měl do pravidla zapsat odkaz, pokud je na výběr dle FL více než jen jedna možnost. Bohužel nemám jak otestovat, že to funguje korektně na jiném než R serveru, takže je vhodno to v budoucnu znovu otestovat.

**Comment by vojir** [comment]
když je k dispozici pouze jedna spojka, tak se již nezobrazuje dialog, ale stále je spojka odkazem - změňte ji prosím na span či něco podobného.

Zároveň je v daném odkazu div (což není moc korektní z hlediska vnořování prvků)

**Comment by PreVaDu** [comment]
Opraveno, v každém případě vnoření divu je způsobené tím, že už cedent má connective uložený s divem, což je divné... Bere se to z FieldGroup.getConnective().
