### ISSUE TITLE
Nezobrazovat dialog pro nastavení binningu při přidání atributu z palety do antecedentu/consequentu

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#42]
Při přetažení atributů z attributes palette je zbytečné se ptát na nastavení koeficientů, a to jak v LM tak i v R verzi.  Mělo by být defaultně subset 1-1

**Comment by PreVaDu** [comment]
Má to být vždy, nebo to bude volitelné v configu? Jaké se mají vyplnit hodnoty, když je to třeba enum? Výchozí první hodnotu?

**Comment by vojir** [comment]
Optimálně v konfigu.

Pokud je k dispozici jen jedna hodnota, měla by být vybrána jako fixed value (jako to funguje nyní), pokud je hodnot k dispozici více, měl by být předvybrán subset 1-1 (resp. "Any value")

**Comment by PreVaDu** [comment]
U Any value tomu rozumím, rovnou se to "odpálí", ale u fixed value ten výběr musíme nechat, ne?
Obecně si nemyslím, že je ideální to tam rovnou vložit s Any value, potom může uživatel přehlídnout možnost změny a bude si myslet, že s tím nic udělat nemůže. Ale pochopitelně to udělám dle požadavků.

**Comment by vojir** [comment]
Přidám nějakou volbu do configu, ale ve výchozím stavu bych byl také pro to, aby byla daná možnost vypnutá - tj. normálně se zobrazil dotaz na spojování.

**Comment by PreVaDu** [comment]
Souhlasím, jen ji dejte, prosím, po dobu testování, na zapnutou. Nebo mi řekněte, kde si to mohu vždy zapnout. :)

**Comment by vojir** [comment]
v konfiguraci je nově doplněna funkce getAutoShowAttributeBinningDialog(), vrací boolean hodnotu, zda se má zobrazit dialog pro nastavení binningu při přidání atributu do vzoru pravidla

**Comment by vojir** [comment]
Možnost zapnout tuto variantu je v config.js
