### ISSUE TITLE
Doladit řazení pravidel v rule clipboard

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#45]
Bylo by vhodné, aby si úlohy v RuleClipboard pamatovaly zvolené řazení pravidel

**Comment by PreVaDu** [comment]
Předpokládám, že se jedná o pamatování si při reloadu. Je pro to asi potřeba doplnit podporu na serveru. Chápu to správně?

**Comment by vojir** [comment]
Ano, chápete to správně - proto to zatím nebylo nikomu přiřazeno. Dodělám příslušnou funkcionalitu v rámci EasyMinerCenter

**Comment by vojir** [comment]
blocked by KIZI/EasyMiner-EasyMinerCenter#80

**Comment by vojir** [comment]
Aktuálně je na serveru doplněna podpora pro ukládání informace o řazení pravidel.
- Řazení probíhá podle měr zajímavosti, či podle hodnoty "default".
- Při zadávání řazení nezáleží na použité velikosti písmen.
- Řazení je možné definovat ručně (doplněna příslušná URL do configu), ale zároveň je hodnota uložena vždycky, když je při požadavku na pravidla z rule clipboard zaslán parametr *order*
- V rámci přehledu úloh v rule clipboard je u každé z úloh nově k dispozici informace o řazení pravidel

**Comment by PreVaDu** [comment]
Děkuji, rozumím. Pár poznámek:

- je možné předávat rulesOrder uppercase? aby to sedělo k hodnotám, které se vkládají do selectu řazení
- ruční ukládání v podstatě nepotřebuji, protože se při změně vždy volá request

**Comment by vojir** [comment]
rules order už je vraceno velkými písmeny

**Comment by PreVaDu** [comment]
Děkuji. Řazení implementováno. Pokud je obdrženo "DEFAULT", nechávám napevno FUI.

**Comment by vojir** [comment]
Ještě jedna opomenutá drobnost - hodnota "DEFAULT" by měla být přidána k měrám zajímavosti, podle kterých má uživatel možnost položky řadit, jako popisek zobrazujme např. "Found order".

**Comment by PreVaDu** [comment]
Aha, to jsem nepochopil. Dobře, takže výchozí (při DEFAULT) bude order markedTasku uložen jako DEFAULT, v URL při stahování rules se nebude odesílat a v UI se zobrazí jako "Found order". Chápu to správně?
Děkuji.

**Comment by vojir** [comment]
Hodnota "default" je normální hodnotou, stejně jako například "fui". Když v požadavku nepošlete nic, tak se použije naposledy použitý způsob řazení. Pokud to chcete změnit na "default", tak odešlete "default".

**Comment by PreVaDu** [comment]
Odešlu-li požadavek na pravidla s řazením DEFAULT (bez ohledu na velikost písma), back-end vrací chybu:
exception 'DibiDriverException' with message 'You have an error in your SQL syntax; check the manual
 that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10' at line 1'
Stejný request s jiným order funguje korektně.

**Comment by vojir** [comment]
problém s DEFAULT řazením opraven v rámci EasyMinerCenter, aktuálně dle testování funguje řazení správně
