### ISSUE TITLE
Úpravy stylů

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#56]
- [x] omezení maximální délky názvů pravidel v rule clipboard (aby nedošlo ke zvětšení daného bloku a tím k rozbití layoutu)
- [x]  při delším názvu položky je rozbité okno pro zadání fixed value u atributu
- [x] problém s načítáním tooltip icon
- [x] sjednocení základních ikon s EasyMinerCenter

**Comment by vojir** [comment]
![err](https://cloud.githubusercontent.com/assets/3865942/7945777/30d4bd34-0973-11e5-858e-f211b83e0b10.png)

**Comment by PreVaDu** [comment]
Nahrál jsem drobnou úpravu, který by mohla trochu pomoct, ale není to 100%, u delších možností se to stejně zalomí na nový řádek.

**Comment by vojir** [comment]
Doplňte tam prosím definici maximální šířky toho selectu (pak nebude přetékat na další řádek).

Jinak bych ještě navrhoval doplnit všem inputům a selectům v dialogových oknech nějaký padding (řekněme "3px 6px").

**Comment by PreVaDu** [comment]
Přidáno. Ta maximální šířka mě nenapadla. Děkuji.
