### ISSUE TITLE
Odkaz pro kompletní odebrání úlohy z RuleClipboard

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#57]

**Comment by PreVaDu** [comment]
Přidat vedle tužtičky pro úpravu názvu tlačítko pro odebrání kompletního tasku - ikonka shodná s odebráním pravidla z tasku. Napojit na API.

**Comment by PreVaDu** [comment]
Momentálně dochází k smazání úlohy v rule clipboard (front-end část) v případě, že již nejsou žádná pravidla v úloze. Má k tomu být přidáno stejné smazání úlohy z RC i na serveru, když už tato funkce je?

**Comment by vojir** [comment]
Aktuálně probíhá v rámci PHP části kontrola přítomnosti úlohy v případě jakéhokoliv přidání/odebrání pravidel, tj. není nutné volat žádnou další funkci navíc.

**Comment by vojir** [comment]
Změnil bych popisek odkazu na "Remove task from Rule clipboard"

**Comment by PreVaDu** [comment]
Zprovozněno. V případě, že se maže úloha, která je aktivní ve FR, zůstanou "zelené fajfky". Mám to řešit, nebo předpokládáme, že se budou mazat neaktivní úlohy?

**Comment by vojir** [comment]
Mělo by dojít k reloadu aktuální stránky FRManageru

**Comment by PreVaDu** [comment]
Doplněno.

**Comment by vojir** [comment]
potvrzuji, že funguje
