### ISSUE TITLE
Při zobrazení overlay okna dojde k vytvoření horizontálního posuvníku

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#58]
Při zobrazení overlay okna (např. preprocessingu) dojde k vytvoření horizontálního posuvníku pro prostor o velikosti cca 10px, který zůstane volný i po jeho zavření.

Pravděpodobně problém s paddingem a šířkou 100%?

**Comment by PreVaDu** [comment]
Nedaří se mi tento problém nasimulovat - jaký prohlížeč? Jaké rozlišení? Je případně, prosím, nějaký screenshot?

**Comment by vojir** [comment]
Dle testování je to chyba ve firefoxu (38.0.5) se zobrazeným doplňkem Web Developer (nástrojovou lištou)

**Comment by PreVaDu** [comment]
Chyba se stávala díky nízkému oknu prohlížeče, žádná souvislost s DevToolbarem.
Stejné chování v Chrome i IE11. Oba se ale vrátily do stavu bez posuvníku při zmizení overlay okna.
Nyní je Chrome i FF ok (není zbytečný posuvník, když nebyl před zobrazením třeba), jen IE11 si zachovává zbytečné přidávání, avšak nezůstává po zavření a tak to nechávám jako nepodstatnou drobnost.

**Comment by vojir** [comment]
OK
