### ISSUE TITLE
Při skrytí atributu v paletě "Attributes" není zobrazen odkaz pro jeho opětovné zobrazení

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#59]

**Comment by PreVaDu** [comment]
- Upravit title "remove" vedle atributu v paletě atributů na "hide".
- Znovu zobrazovat odkaz pro zobrazení skrytých atributů.

**Comment by PreVaDu** [comment]
Snažil jsem se dohledat čím se to pokazilo, když to bylo dřív ok, neúspěšně.
Přidal jsem tedy zobrazení a skrytí na patřičná místa a zrušil kontrolu, která to špatně vyhodnocovala. Je možné, že je problém ve stylu vykreslování, že už nemáme tolik reloadů nebo něco takového, skutečně nevím. Pokud to ale bude fungovat, tak bych to asi neřešil.

**Comment by vojir** [comment]
Potvrzuji, že funguje. Nešlo by to ale udělat bez reloadu celého UI?

**Comment by PreVaDu** [comment]
Ten tam byl a nevím vůbec proč. :( ARBuilder.js ř. 346 volá reloadData, mohu dát reloadAttributes (ř. 300), ale to má u sebe nějaké TODO a dělá to to samé - reloaduje Data.

Divné je, že DataDescription.js vrací u funkce hasHiddenAttributes (ř. 124) vždy 0. Přitom když si vypíšu keys toho allHiddenAttributes, mám tam vždy 22, this.$id je také vždy 22. Díky tomu nefunguje pořádně kontrola.

Celé skrývání je postavené na ukládání prvků do storage. Nechápu ten princip, proč to nemůže být obyčejné skrytí prvku? Bylo by to snažší, přirozenější a méně náchylné na chybu. Ale co hlavně nechápu je jak se to vlastně stalo, že to přestalo fungovat, kdy, v jaké verzi. Procházel jsem historii GIT a nic tomu nenasvědčuje.

**Comment by vojir** [comment]
Aha... Tak to budeme muset ještě nějak poladit - správně se to mělo ukládat na server (funkcí, která v praxi vlastně nic neukládala - tj. byla před několika měsíci zrušena). 

Z hlediska zobrazení skrytých atributů to zatím nechte s tím reloadem. Připravím v rámci EasyMinerCenter funkci pro ukládání nastavení ke konkrétnímu mineru.

**Comment by vojir** [comment]
Blocked by KIZI/EasyMiner-EasyMinerCenter#79

**Comment by PreVaDu** [comment]
Možná přestalo zobrazování odkazu fungovat tím zrušením ukládání. Budeme to muset asi celé předělat. ;)

**Comment by vojir** [comment]
Na straně EasyMinerCenter připravena podpora pro ukládání nastavení mineru - adresy jsou v configu.

**Comment by PreVaDu** [comment]
Funkce přepsána do nové podoby
- používá uložení na serveru
- JS ukládá v proměnné bez localStorage
- skrytí pouze pomocí přidání třídy hidden

Zároveň byl upraven Config (config.latte na serverové části), byl o tom zaslán mail.

**Comment by vojir** [comment]
Bylo nutné opravit DataDescription.js (je nutné počítat s minerem, který nemá na serveru uloženou žádnou informaci o skrytých atributech). Zbytek ještě dootestuji.

**Comment by PreVaDu** [comment]
To jsem si neuvědomil, děkuji.
