### ISSUE TITLE
CSV se špatně importuje pokud hlavička CSV obsahuje prázdný název sloupce

### ISSUE THREAD

**Issue by kliegr** [KIZI/EasyMiner-MiningUI#64]
Příklad csv

`,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title
0,7,648,4,978234737,M,35,1,06810,Mission: Impossible (1996)`

Poslední sloupec není importován.

**Comment by vojir** [comment]
Chybné zařazení - přesunuto do https://github.com/KIZI/EasyMiner-EasyMinerCenter/issues/83
