### ISSUE TITLE
Nefunguje dialog pro přejmenování rule setu

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#65]
- je zde zobrazen nesmyslný text "Nějaký popisek"
- při pokusu o uložení je v konzoli hlášena chyba o chybějícím prvku description, změna se neprovede a okno se nezavře

**Comment by PreVaDu** [comment]
Omlouvám se za hloupou chybu.
1) opraveno
2) opraveno, upravil jsem opět config.latte
Snad jsem to stihl před prezentací.
