### ISSUE TITLE
Doladění funkčnosti Rule Clipboard a Knowledge Base

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#66]
* [x] při kliknutí na aktuální rule set (tj. na první položku v seznamu) by mělo dojít k zavření okna - aktuálně není vyvolána žádná akce
* [x] v okně pro přejmenování rule setu je chybný nadpis
* [x] v okně pro přejmenování rule setu zvětšete velikost vstupních polí pro název i pro popis (u popisu by možná bylo vhodné použít textarea
![renameknowledgebase](https://cloud.githubusercontent.com/assets/3865942/9150969/e25320b6-3df1-11e5-9a2d-33dcdc614bd9.png)
* [x] při překreslení knowledge base dojde k rozbití layoutu:
![img](https://cloud.githubusercontent.com/assets/3865942/9229258/8207235a-411c-11e5-85f3-1baf2e61fe2d.png)
* [ ] problém s označením aktuální strany v rámci stránkovače

**Comment by vojir** [comment]
K chybě s layoutem dojde v případě, kdy je zobrazena knowledge base, je zobrazen rule set s větším množstvím pravidel a přes změnu rule setu je vyměněn za rule set s menším počtem pravidel.
Chyba se projevuje v posledních verzích Firefoxu i Chrome.

**Comment by PreVaDu** [comment]
Setrvává chyba stále? Poslední verze FF i Chrome a nic takového nepozoruji. Může to souviset se scrollováním na původní místo, ale u mě se to chová korektně. Měním z rulesetu s 19 pravidly (stránkování, ale dal jsem si i výpis všech) na ruleset s 1.

**Comment by vojir** [comment]
Chyba přetrvává stále, testováno ve FF 40.0.2 na win 10. Zároveň po prvním projevu chyby se chyba objevuje i při stránkování. 

Zároveň mi aktuálně nefunguje označení aktuální aktivní stránky rule clipboard při větším množství stran (aktuálně 3). I když se načte další strana pravidel, tak je označená vždy 1.

**Comment by PreVaDu** [comment]
Tak konečně nasimulováno - jedná se o případ, kdy je overlay se změnou rulesetu vyšší než viditelná oblast, v takovém případě dojde k rozhození a je jedno, jestli je ruleset velký, nebo malý. Podívám se na to.

Označení aktuální stránky nefunguje v KB, v rule clipboard tuto chybu nepozoruji. V KB nejde kvůli tomu, že z back-endu nedostávám s JSON s rulesCount (dříve jsem dostával, u MR tuto informaci dostávám).

**Comment by vojir** [comment]
Ještě prosím to označení aktuální stránky v KB. Počet pravidel v daném rulesetu je vracen v každém seznamu pravidel:
```
{"ruleset":{"id":5,"name":"Stanislav Vojíř","description":"","rulesCount":21},"rules":{"1487054":{"id"
:1487054,"text":"language(English_language) & country(United_States) & mediaType(Paperback) → rating(0)","a":3658,"b":2533,"c":35524,"d":30656,"selected":"0"}}}
```

**Comment by PreVaDu** [comment]
tak nakonec chyba jinde... děkuji a opraveno :)
