### ISSUE TITLE
Add all link in the attributes palette is broken

### ISSUE THREAD

**Issue by kliegr** [KIZI/EasyMiner-MiningUI#67]
Clicking on Add all link adds only one attributte

**Comment by PreVaDu** [comment]
@vojir Problém je pouze u atributu amount pod účtem p. Zemana. Při přidání tohoto atributu je category String,
![amount-category1](https://cloud.githubusercontent.com/assets/7348640/9276104/48cc268a-42a2-11e5-841f-a6f84d436ca4.jpg)

při hromadném přidání se bere jako int.
![amount-category2](https://cloud.githubusercontent.com/assets/7348640/9276105/4b695c64-42a2-11e5-8d19-ab842497a53a.jpg)

Nepodařilo se mi zjistit, zda je stejná chyba i na dev verzi...

**Comment by PreVaDu** [comment]
@vojir v podstatě asi stačí category změnit vždy na String:
http://mootools.net/core/docs/1.4.5/Types/String#String:String-from
