### ISSUE TITLE
Dialog pro export výsledků z rule clipboard/knowledge base

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#70]
U každé úlohy v rule clipboard a v knowledge base by měl přibýt odkaz pro zobrazení možností exportu výsledků (za odkazem pro zobrazení detailů úlohy).

Odkazy pro zobrazení by měly vypadat obdobně, jako u dialogu pro změnu rule setu. Seznam potřebných odkazů je v configu.

**Comment by PreVaDu** [comment]
Hotovo. Má být okno širší?

**Comment by vojir** [comment]
Tato velikost je OK, časem tam možná doplníme nějaké vysvětlení variant exportu.
