### ISSUE TITLE
Přidání checkboxů u data fields pro hromadné přidání

### ISSUE THREAD

**Issue by PreVaDu** [KIZI/EasyMiner-MiningUI#75]
Dle domluvy jsem nachystal první verzi grafického řešení spolu s možnou funkčností checkboxů pro hromadné přidání data fields do atributů.
Inspiroval jsem se použitým řešením u found rules atd.
Momentálně vše končí tak, že se do konzole vypisují IDčka checkboxů.
Budete chtít do backendu obdržet čisté názvy, nebo si je od suffixů očistíte? Ono není asi moc ideální operovat s názvem, ale v APFieldu nevidím nic unikátního, dle čeho to rozpoznávat...

**Comment by vojir** [comment]
Doplňte prosím možnost vybrat vše/invertovat výběr (jako u checkboxů v rámci discovered rules). 
Budeme pracovat s názvy, odstraňte z nich prosím tu část "-checkbox"

**Comment by vojir** [comment]
ještě prosím upravte zarovnání checkboxů s ohledem na textové názvy data fields - aktuálně začíná checkbox "pod linkou"

**Comment by PreVaDu** [comment]
upraveno, opraveno.

**Comment by vojir** [comment]
Identifikace prostřednictvím ID daného inputu nefunguje korektně!
- hodnotou ID by neměl být jen název sloupce, měla by být využita nějaká předpona (jakožto prevence konfliktních ID v rámci aplikace)
- identifikační ID je v některých případech odlišné od názvu sloupce - například u sloupce "birth_year" je vracena hodnota "birthyear"

**Comment by PreVaDu** [comment]
1) Z toho důvodu tam byl původně sufix "-checkbox". Dle připomínek byl odstraněn. Bude v rámci datafields název vždy unikátní? Pak by takový sufix měl stačit.
2) Lze mi přiřadit miner, který daný sloupec používá? Abych vyzkoušel přímo na něm (a nemohlo dojít k jinému chování simulováním s jinými daty). Děkuji.

**Comment by vojir** [comment]
- v data fields jsou jednotlivé názvy vždy unikátní
- minery již mezi uživateli vzájemně přehazovat nejdou, birth_year je jeden z výchozích sloupců z loans.csv

problém je pravděpodobně způsoben již samotným použitím "id" jakožto identifikátoru... Lepší by patrně bylo buď použití proměnné v JS (jako je tomu například u zobrazení histogramů atp.), nebo použití atributu data-*

**Comment by vojir** [comment]
Ještě jeden problém - ovládací prvky pro výběr všech či žádného sloupce pro předzpracování se zobrazí až při ručním vybrání některého ze sloupců. Správně by se měly zobrazovat hned při aktivaci multivýběru...
 
![datafields](https://cloud.githubusercontent.com/assets/3865942/10865053/dff7743e-7fff-11e5-95fe-bf9a6ba42a7d.jpg)

**Comment by PreVaDu** [comment]
Děkuji za feedback. Podívám se na to.

**Comment by PreVaDu** [comment]
Všechny chyby by měly být opraveny.
