### ISSUE TITLE
Odkaz pro možnost vymazání zadání vzoru pravidla

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#78]
Aktuálně není v aplikaci k dispozici žádná možnost jednoduchého "vyresetování" zadání úlohy. Tj. pokud uživatel např. pomocí funkce "add all" přidá do vzoru pravidla velké množství atributů, musí je jednotlivě odstraňovat, nebo ručně reloadovat okno.

Bylo by fajn, kdyby měl uživatel k dispozici odkaz "remove all".

**Comment by PreVaDu** [comment]
![empty_cedent](https://cloud.githubusercontent.com/assets/7348640/11540441/15ae688a-992d-11e5-97e6-7e4428e39270.jpg)
křížek jako při mazání atributu

**Comment by vojir** [comment]
při kliknutí na křížek je vyhazována chyba:
```
TypeError: this.elements[0] is undefined 
var parent = this.elements[0].getParent();
```

(minimálně při kliknutí při prázdném antecedentu/consequentu)

**Comment by PreVaDu** [comment]
Ano, při prázdném, ale nevím, zda to není tím, že nejsou žádné atributy v paletě atributů. Počkám, až bude zpět funkčnost back-endu a pak to ještě jednou pořádně otestuji.

**Comment by vojir** [comment]
pokud paleta atributů není prázdná, projevuje se chyba po prvním úspěšném vyprázdnění consequentu...

**Comment by PreVaDu** [comment]
V mailu mi nepřišla druhá věta komentáře a tak jsem nahrál na FTP opravu. Změnil jsem jen UIListener a co bylo změněno na FTP jsem do toho zahrnul. Počkám až to tedy bude sloučené a případně ještě učešu. Momentálně ale tlačítko nic nedělá, je-li antecedent/consequent prázdný.

**Comment by vojir** [comment]
sloučeno
