### ISSUE TITLE
Hromadná práce s atributy by se měla chovat stejně, jako u data fields

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#79]
- stejné chování jako datafields a add selected
- nově výběr, jestli do antecedentu, nebo consequentu
- odkaz bude jeden, když jsou zatržítka, je "add all" s výběrem a nynějším chováním, kdy "add selected", tak jako u datafields (a výběr)

**Comment by PreVaDu** [comment]
Chci se raději ujistit, abych to neudělal špatně:

1) odkaz add selected se zobrazí jen při nějakém zaškrtnutém checkboxu, jinak se na jeho místě zobrazuje "add all" - add all ale postrádá smysl, protože je "Select all" fce
2) "Show hidden" zůstane o řádek výš, když budou checkboxy?
3) při hromadném přídání bude overlay na výběr do které části pravidla to má být přidáno a pak ještě druhý overlay na výběr "Merging type"? Nebo bude něco při tomto úkonu automaticky vybráno?

Děkuji.

**Comment by vojir** [comment]
Upřesnění:
1) ano, "add selected" se zobrazí jen při nějakém zaškrtnutém checkboxu; pokud nejsou zobrazené checkboxy, mělo by tam být "add unused" - tedy pokud jsou v paletě nějaké atributy, které ještě nebyly použity do vzoru pravidla (což je chování současného odkazu, který tam je)
2) ano, show hidden bych klidně zobrazil o řádek výš
3) zobrazí se jen overlay na výběr části pravidla, kam mají být atributy přidány; merging type se detekuje automaticky (na to už je tam hotová funkce)

**Comment by PreVaDu** [comment]
Hotovo, otestovány i kombinace se skrytými atributy atd., ale zobrazení odkazů ovlivňuje několik míst, tak snad to je bez skryté chyby.
