### ISSUE TITLE
Rozbitý layout okna pro výběr hodnoty atributu

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#81]
- [x] nastavení min a max width pro selecty
- [x] odstranění otazníčku s nápovědou (obdobně, jako u IMs)
![screen](https://cloud.githubusercontent.com/assets/3865942/11329001/331a9352-9195-11e5-809c-fe72436a6cda.jpg)

**Comment by PreVaDu** [comment]
Problém vznikl definováním šířky pro všechny inputy a selecty v easyminercenter stylech (na Githubu pravděpodobně ještě nejsou commitnuté).
Bude definice finální? Pokud ano, nastavíme v UI šířku na auto (pravděpodobně pro overlay, nenašel jsem jiné místo, kde by to dělalo problém).
