### ISSUE TITLE
Úprava okna pro zadání interest measures

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-MiningUI#9]
V rámci okna pro zadání interest measures by se měla zobrazovat nápověda k vybrané míře zajímavosti (jak při přidání nové míry zajímavosti, tak při editaci prahových hodnot).

Aktuálně se nápověda k míře zajímavosti zobrazuje pod otazníkem při přidání nové míry zajímavosti, při změně se nezobrazuje. Přesuňme tuto nápovědu do normálně viditelného odstavce (menším písmem, šedivě).

Např.: 
![screen](https://cloud.githubusercontent.com/assets/3865942/9344453/024b41cc-4609-11e5-8084-7b97b7df14b0.png)

Zároveň je potřeba upravit zarovnání stávajících prvků daného okna.

**Comment by PreVaDu** [comment]
Udělal jsem první návrh. Mám pár poznámek:
1) zarovnání je s levým okrajem, není možné zarovnat spolehlivě s labelem, jelikož má text-align right a u jiného labelu by to stejně nesedělo (viz 2)
2) řešení je lehce rozšiřitelné na další okna, kde je podobná nápověda, bylo by to možná vhodné udělat i jinde

**Comment by vojir** [comment]
- Změňte prosím barvu na tmavší šedivou, či o 1-2px  zvětšete písmo (aby se to lépe četlo).
- Spíše bych byl pro zarovnání labelů na levou stranu - takto to vypadá dost neupraveně, když jsou tam 3 položky a každá začíná jinde.

**Comment by PreVaDu** [comment]
Upravil jsem. Rovnou jsem upravil i další styly (selectu a em), aby to trochu vypadalo. Bylo to dlouhodobě neučesané. Snad se to neprojevilo negativně i na místě, na které jsem zapomněl.

Když na to teď koukám, dal bych close overlaye absolute napravo nahoru, nyní je relative a nadpis se vykresluje až pod ním. Vzniká tam nepřirozená mezera, která je zbytečná. Co myslíte?

**Comment by vojir** [comment]
Ohledně umístění tlačítka close v normálních dialozích určitě souhlas, u
iframů bych ho nechal nahoře (aby nedocházelo ke konfliktu s posuvníkem).

Dne 21. srpna 2015 23:45 Přemysl Václav Duben <notifications@github.com>
napsal(a):

**Comment by PreVaDu** [comment]
Uděláme to odlišením dle ID overlayů, nebo speciální třídou?

**Comment by vojir** [comment]
S ohledem na to, že velikosti jednotlivých překryvných oken jsou zapsány ve stylech pomocí ID, byl bych pro zachování ID také pro pozici zavíracího tlačítka. Možný by bylo vhodné pro to definovat stylus mixin.

Alternativně mne napadá možnost definovat to pomocí přidání margin-top pro ten iframe, pak by mohl mít zavírací odkaz vždy absolutně definovanou pozici.

**Comment by PreVaDu** [comment]
Podíval jsem se na to blíže a pomocí top -20px je to vlastně umístěno skoro jako absolute. Vzdálenost nadpisu od horní hrany je dán paddingem overlay boxu.
Tudíž nemá smysl to měnit na absolute. Teoreticky stačí pouze zmenšit padding, pokud to bude žádoucí.

**Comment by vojir** [comment]
aktuálně vyhovuje...
